// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/antonmisa/1cctl/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// CtrlPipe is an autogenerated mock type for the CtrlPipe type
type CtrlPipe struct {
	mock.Mock
}

// DeleteConnection provides a mock function with given fields: ctx, entrypoint, cluster, connection, clusterCred
func (_m *CtrlPipe) DeleteConnection(ctx context.Context, entrypoint string, cluster entity.Cluster, connection entity.Connection, clusterCred entity.Credentials) error {
	ret := _m.Called(ctx, entrypoint, cluster, connection, clusterCred)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entity.Cluster, entity.Connection, entity.Credentials) error); ok {
		r0 = rf(ctx, entrypoint, cluster, connection, clusterCred)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteConnections provides a mock function with given fields: ctx, entrypoint, cluster, connections, clusterCred
func (_m *CtrlPipe) DeleteConnections(ctx context.Context, entrypoint string, cluster entity.Cluster, connections []entity.Connection, clusterCred entity.Credentials) error {
	ret := _m.Called(ctx, entrypoint, cluster, connections, clusterCred)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entity.Cluster, []entity.Connection, entity.Credentials) error); ok {
		r0 = rf(ctx, entrypoint, cluster, connections, clusterCred)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteSession provides a mock function with given fields: ctx, entrypoint, cluster, session, clusterCred
func (_m *CtrlPipe) DeleteSession(ctx context.Context, entrypoint string, cluster entity.Cluster, session entity.Session, clusterCred entity.Credentials) error {
	ret := _m.Called(ctx, entrypoint, cluster, session, clusterCred)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entity.Cluster, entity.Session, entity.Credentials) error); ok {
		r0 = rf(ctx, entrypoint, cluster, session, clusterCred)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteSessions provides a mock function with given fields: ctx, entrypoint, cluster, sessions, clusterCred
func (_m *CtrlPipe) DeleteSessions(ctx context.Context, entrypoint string, cluster entity.Cluster, sessions []entity.Session, clusterCred entity.Credentials) error {
	ret := _m.Called(ctx, entrypoint, cluster, sessions, clusterCred)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entity.Cluster, []entity.Session, entity.Credentials) error); ok {
		r0 = rf(ctx, entrypoint, cluster, sessions, clusterCred)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DisableSessions provides a mock function with given fields: ctx, entrypoint, cluster, infobase, clusterCred, infobaseCred, code
func (_m *CtrlPipe) DisableSessions(ctx context.Context, entrypoint string, cluster entity.Cluster, infobase entity.Infobase, clusterCred entity.Credentials, infobaseCred entity.Credentials, code string) error {
	ret := _m.Called(ctx, entrypoint, cluster, infobase, clusterCred, infobaseCred, code)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entity.Cluster, entity.Infobase, entity.Credentials, entity.Credentials, string) error); ok {
		r0 = rf(ctx, entrypoint, cluster, infobase, clusterCred, infobaseCred, code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EnableSessions provides a mock function with given fields: ctx, entrypoint, cluster, infobase, clusterCred, infobaseCred, code
func (_m *CtrlPipe) EnableSessions(ctx context.Context, entrypoint string, cluster entity.Cluster, infobase entity.Infobase, clusterCred entity.Credentials, infobaseCred entity.Credentials, code string) error {
	ret := _m.Called(ctx, entrypoint, cluster, infobase, clusterCred, infobaseCred, code)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entity.Cluster, entity.Infobase, entity.Credentials, entity.Credentials, string) error); ok {
		r0 = rf(ctx, entrypoint, cluster, infobase, clusterCred, infobaseCred, code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetClusters provides a mock function with given fields: ctx, entrypoint
func (_m *CtrlPipe) GetClusters(ctx context.Context, entrypoint string) ([]entity.Cluster, error) {
	ret := _m.Called(ctx, entrypoint)

	var r0 []entity.Cluster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]entity.Cluster, error)); ok {
		return rf(ctx, entrypoint)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []entity.Cluster); ok {
		r0 = rf(ctx, entrypoint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Cluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, entrypoint)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetConnections provides a mock function with given fields: ctx, entrypoint, cluster, infobase, clusterCred
func (_m *CtrlPipe) GetConnections(ctx context.Context, entrypoint string, cluster entity.Cluster, infobase entity.Infobase, clusterCred entity.Credentials) ([]entity.Connection, error) {
	ret := _m.Called(ctx, entrypoint, cluster, infobase, clusterCred)

	var r0 []entity.Connection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entity.Cluster, entity.Infobase, entity.Credentials) ([]entity.Connection, error)); ok {
		return rf(ctx, entrypoint, cluster, infobase, clusterCred)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, entity.Cluster, entity.Infobase, entity.Credentials) []entity.Connection); ok {
		r0 = rf(ctx, entrypoint, cluster, infobase, clusterCred)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Connection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, entity.Cluster, entity.Infobase, entity.Credentials) error); ok {
		r1 = rf(ctx, entrypoint, cluster, infobase, clusterCred)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetInfobases provides a mock function with given fields: ctx, entrypoint, cluster, clusterCred
func (_m *CtrlPipe) GetInfobases(ctx context.Context, entrypoint string, cluster entity.Cluster, clusterCred entity.Credentials) ([]entity.Infobase, error) {
	ret := _m.Called(ctx, entrypoint, cluster, clusterCred)

	var r0 []entity.Infobase
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entity.Cluster, entity.Credentials) ([]entity.Infobase, error)); ok {
		return rf(ctx, entrypoint, cluster, clusterCred)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, entity.Cluster, entity.Credentials) []entity.Infobase); ok {
		r0 = rf(ctx, entrypoint, cluster, clusterCred)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Infobase)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, entity.Cluster, entity.Credentials) error); ok {
		r1 = rf(ctx, entrypoint, cluster, clusterCred)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSessions provides a mock function with given fields: ctx, entrypoint, cluster, infobase, clusterCred
func (_m *CtrlPipe) GetSessions(ctx context.Context, entrypoint string, cluster entity.Cluster, infobase entity.Infobase, clusterCred entity.Credentials) ([]entity.Session, error) {
	ret := _m.Called(ctx, entrypoint, cluster, infobase, clusterCred)

	var r0 []entity.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entity.Cluster, entity.Infobase, entity.Credentials) ([]entity.Session, error)); ok {
		return rf(ctx, entrypoint, cluster, infobase, clusterCred)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, entity.Cluster, entity.Infobase, entity.Credentials) []entity.Session); ok {
		r0 = rf(ctx, entrypoint, cluster, infobase, clusterCred)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, entity.Cluster, entity.Infobase, entity.Credentials) error); ok {
		r1 = rf(ctx, entrypoint, cluster, infobase, clusterCred)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCtrlPipe creates a new instance of CtrlPipe. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCtrlPipe(t interface {
	mock.TestingT
	Cleanup(func())
}) *CtrlPipe {
	mock := &CtrlPipe{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
