app:
  path_to_rac: "C:/Program Files/1cv8/8.3.14.1857/bin/rac.exe"
  path_to_1c: "C:/Program Files/1cv8/8.3.14.1857/bin/1cv8.exe"
  lock_code: "12345" 

http:
  port: '8080'

cache:
  ttl: 60s

trace:
  enable: true
  endpoint: "http://localhost:14268/api/traces"

logger:
  level: "debug"
  path: "./logs/current.log"  