basePath: /v1
definitions:
  entity.Cluster:
    properties:
      errth:
        example: 0
        type: integer
      exp:
        example: 1200
        type: integer
      host:
        example: localhost
        type: string
      id:
        example: UUID
        type: string
      kpp:
        example: 0
        type: integer
      lb:
        example: perfomance
        type: string
      lt:
        example: 3000
        type: integer
      mms:
        example: 50000
        type: integer
      mmts:
        example: 600
        type: integer
      name:
        example: name
        type: string
      port:
        example: "1541"
        type: string
      sftl:
        example: 0
        type: integer
      sl:
        example: 0
        type: integer
    type: object
  entity.Connection:
    properties:
      appid:
        example: 1CV8
        type: string
      blocked:
        example: 0
        type: integer
      cid:
        example: 12345
        type: integer
      connected:
        example: 2023-08-10T11:40:55
        type: string
      host:
        example: localhost
        type: string
      ib:
        example: UUID
        type: string
      id:
        example: UUID
        type: string
      proc:
        example: UUID
        type: string
      sid:
        example: 12345
        type: integer
    type: object
  entity.Infobase:
    properties:
      desc:
        example: comments
        type: string
      id:
        example: UUID
        type: string
      name:
        example: name
        type: string
    type: object
  entity.Session:
    properties:
      active:
        example: 2023-08-10T14:04:43
        type: string
      appid:
        example: 1CV8
        type: string
      blockdb:
        example: 0
        type: integer
      blockls:
        example: 0
        type: integer
      bytes:
        example: 12345
        type: integer
      bytes5m:
        example: 123
        type: integer
      bytesdb:
        example: 123
        type: integer
      bytesdb5m:
        example: 12
        type: integer
      calls:
        example: 5
        type: integer
      calls5m:
        example: 2
        type: integer
      conn:
        example: UUID
        type: string
      cpu:
        example: 1234
        type: integer
      cpu5m:
        example: 12
        type: integer
      cpucur:
        example: 123
        type: integer
      dbproc:
        example: 123
        type: integer
      dbprocat:
        example: ""
        type: string
      dbproci:
        example: ""
        type: string
      dur:
        example: 100
        type: integer
      dur5m:
        example: 100
        type: integer
      durcur:
        example: 80
        type: integer
      durcurdb:
        example: 80
        type: integer
      durdb:
        example: 100
        type: integer
      durdb5m:
        example: 100
        type: integer
      dursvc:
        example: 0
        type: integer
      dursvc5m:
        example: 0
        type: integer
      dursvccur:
        example: 0
        type: integer
      hib:
        example: yes/no
        type: string
      hibterm:
        example: 3600
        type: integer
      hibtm:
        example: 1200
        type: integer
      host:
        example: Host
        type: string
      ib:
        example: UUID
        type: string
      id:
        example: UUID
        type: string
      loc:
        example: ru
        type: string
      mem:
        example: 123456
        type: integer
      mem5m:
        example: 1234
        type: integer
      memcur:
        example: 12345
        type: integer
      proc:
        example: UUID
        type: string
      read:
        example: 56789
        type: integer
      read5m:
        example: 56
        type: integer
      readcur:
        example: 5678
        type: integer
      sep:
        example: ""
        type: string
      sid:
        example: 12345
        type: integer
      started:
        example: 2023-08-10T14:04:43
        type: string
      svc:
        example: Name
        type: string
      uname:
        example: UserName
        type: string
      write:
        example: 123
        type: integer
      write5m:
        example: 123
        type: integer
      writecur:
        example: 123
        type: integer
    type: object
  error.response:
    properties:
      error:
        example: message
        type: string
    type: object
  v1.clusterResponse:
    properties:
      clusters:
        items:
          $ref: '#/definitions/entity.Cluster'
        type: array
    type: object
  v1.connectionResponse:
    properties:
      connections:
        items:
          $ref: '#/definitions/entity.Connection'
        type: array
    type: object
  v1.infobaseResponse:
    properties:
      infobases:
        items:
          $ref: '#/definitions/entity.Infobase'
        type: array
    type: object
  v1.sessionResponse:
    properties:
      sessions:
        items:
          $ref: '#/definitions/entity.Session'
        type: array
    type: object
host: localhost:8080
info:
  contact: {}
  description: Using a 1C cluster control service over http
  title: 1C cluster control service
  version: "1.0"
paths:
  /cluster/:cluster/connection/list:
    get:
      description: Show all connections with identifiers for current cluster
      operationId: connections
      parameters:
      - description: UUID of cluster
        in: path
        name: cluster
        required: true
        type: string
      - description: Firstly try to find from Cache
        in: query
        name: cache
        type: boolean
      - description: Entrypoint for cluster
        in: query
        name: entrypoint
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.connectionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.response'
      summary: Show all connections in cluster
      tags:
      - connection list
  /cluster/:cluster/infobase/:infobase/connection/list:
    get:
      description: Show all connections with identifiers for current infobase in cluster
      operationId: connectionsByInfobase
      parameters:
      - description: UUID of cluster
        in: path
        name: cluster
        required: true
        type: string
      - description: UUID of infobase
        in: path
        name: infobase
        required: true
        type: string
      - description: Firstly try to find from Cache
        in: query
        name: cache
        type: boolean
      - description: Entrypoint for cluster
        in: query
        name: entrypoint
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.connectionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.response'
      summary: Show all connections in infobase
      tags:
      - connection list infobase
  /cluster/:cluster/infobase/:infobase/session/list:
    get:
      description: Show all sessions with identifiers for current infobase in cluster
      operationId: sessionsByInfobase
      parameters:
      - description: UUID of cluster
        in: path
        name: cluster
        required: true
        type: string
      - description: UUID of infobase
        in: path
        name: infobase
        required: true
        type: string
      - description: Firstly try to find from Cache
        in: query
        name: cache
        type: boolean
      - description: Entrypoint for cluster
        in: query
        name: entrypoint
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.sessionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.response'
      summary: Show all sessions in infobase
      tags:
      - session list infobase
  /cluster/:cluster/infobase/list:
    get:
      description: Show all infobases with identifiers for current cluster
      operationId: infobases
      parameters:
      - description: UUID of cluster
        in: path
        name: cluster
        required: true
        type: string
      - description: Firstly try to find from Cache
        in: query
        name: cache
        type: boolean
      - description: Entrypoint for cluster
        in: query
        name: entrypoint
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.infobaseResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.response'
      summary: Show all infobases in cluster
      tags:
      - infobase list
  /cluster/:cluster/session/list:
    get:
      description: Show all sessions with identifiers for current cluster
      operationId: sessions
      parameters:
      - description: UUID of cluster
        in: path
        name: cluster
        required: true
        type: string
      - description: Firstly try to find from Cache
        in: query
        name: cache
        type: boolean
      - description: Entrypoint for cluster
        in: query
        name: entrypoint
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.sessionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.response'
      summary: Show all sessions in cluster
      tags:
      - session list
  /cluster/list:
    get:
      description: Show all clusters with data
      operationId: clusters
      parameters:
      - description: Firstly try to find from Cache
        in: query
        name: cache
        type: boolean
      - description: Entrypoint for cluster
        in: query
        name: entrypoint
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.clusterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.response'
      summary: Show clusters
      tags:
      - cluster list
swagger: "2.0"
